# Ones and Zeros

In [1]:
import numpy as np

x = np.empty([3, 3], np.uint8)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [2]:
y = np.eye(5, dtype=np.uint8)
print(y)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [3]:
y = np.eye(5, dtype=np.uint8, k=1)
print(y)

[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [4]:
y = np.eye(5, dtype=np.uint8, k=-1)
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


In [5]:
x = np.identity(5, dtype= np.uint8)
print(x)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [6]:
x = np.ones((2, 5, 5), dtype=np.int16)
print(x)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [7]:
x = np.zeros((2, 5, 5, 2), dtype=np.int16)
print(x)

[[[[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]]


 [[[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]]]


In [8]:
x = np.full((3, 3, 3), dtype=np.int16, fill_value = 5)
print(x)

[[[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]]


# Matrix creation routines

In [9]:
x = np.tri(3, 3, k=0, dtype=np.uint16)
print(x)

[[1 0 0]
 [1 1 0]
 [1 1 1]]


In [10]:
x = np.tri(5, 5, k=1, dtype=np.uint16)
print(x)

[[1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [11]:
x = np.tri(5, 5, k=-1, dtype=np.uint16)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [12]:
x = np.ones((5, 5), dtype=np.uint8)
y = np.tril(x, k=-1)
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [13]:
x = np.ones((5, 5), dtype=np.uint8)
y = np.triu(x, k=0)
print(y)

[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]


In [14]:
x = np.ones((5, 5), dtype=np.uint8)
y = np.triu(x, k=-1)
print(y)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]]


In [15]:
x = np.ones((5, 5), dtype=np.uint8)
y = np.triu(x, k=1)
print(y)

[[0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]
